/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['Geist Mono', 'SF Mono', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // CXSAMAA Design Tokens
        brand: {
          green: '#00d4a4',
          'green-deep': '#00b88e',
          'green-soft': 'rgba(0, 212, 164, 0.12)',
          'green-glow': 'rgba(0, 212, 164, 0.25)',
          blue: '#3772cf',
          tag: '#3772cf',
          error: '#ef4444',
          warn: '#f59e0b',
        },
        canvas: {
          DEFAULT: '#fafbfc',
          dark: '#0a0a0a',
          pure: '#ffffff',
        },
        surface: {
          DEFAULT: '#f3f4f6',
          soft: '#f9fafb',
          elevated: '#ffffff',
          code: '#1e1e1e',
          'dark-card': '#141414',
        },
        hairline: {
          DEFAULT: '#e5e7eb',
          soft: '#f0f0f0',
          dark: '#2a2a2a',
        },
        ink: '#111827',
        charcoal: '#374151',
        slate: '#6b7280',
        steel: '#9ca3af',
        stone: '#d1d5db',
        'on-dark': {
          DEFAULT: '#ffffff',
          muted: 'rgba(255, 255, 255, 0.6)',
          subtle: 'rgba(255, 255, 255, 0.35)',
        },
        semantic: {
          success: '#00d4a4',
          error: '#ef4444',
          warning: '#f59e0b',
          info: '#3772cf',
        },
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
      fontSize: {
        'hero-display': ['72px', { lineHeight: '1.05', letterSpacing: '-2px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '600' }],
        'heading-1': ['48px', { lineHeight: '1.10', letterSpacing: '-1px', fontWeight: '600' }],
        'heading-2': ['36px', { lineHeight: '1.20', letterSpacing: '-0.5px', fontWeight: '600' }],
        'heading-3': ['28px', { lineHeight: '1.25', fontWeight: '600' }],
        'heading-4': ['22px', { lineHeight: '1.30', fontWeight: '600' }],
        'heading-5': ['18px', { lineHeight: '1.40', fontWeight: '600' }],
        'subtitle': ['18px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-md-medium': ['16px', { lineHeight: '1.50', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-sm-medium': ['14px', { lineHeight: '1.50', fontWeight: '500' }],
        'caption': ['13px', { lineHeight: '1.40', fontWeight: '400' }],
        'caption-bold': ['13px', { lineHeight: '1.40', fontWeight: '600' }],
        'micro': ['12px', { lineHeight: '1.40', fontWeight: '500' }],
        'micro-uppercase': ['11px', { lineHeight: '1.40', letterSpacing: '0.5px', fontWeight: '600' }],
        'button-md': ['14px', { lineHeight: '1.30', fontWeight: '500' }],
        'code-md': ['14px', { lineHeight: '1.50', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '1.40', fontWeight: '400' }],
        'code-inline': ['13px', { lineHeight: '1.30', fontWeight: '500' }],
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '40px',
        'section-sm': '48px',
        'section': '64px',
        'section-lg': '96px',
        'hero': '120px',
      },
      maxWidth: {
        'container': '1280px',
      },
      boxShadow: {
        'xs': 'rgba(0, 0, 0, 0.04) 0px 1px 2px 0px',
        'card': 'rgba(0, 0, 0, 0.08) 0px 4px 12px 0px',
        'mockup': 'rgba(0, 0, 0, 0.12) 0px 24px 48px -8px',
        'brand-glow': 'rgba(0, 212, 164, 0.08) 0px 8px 24px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "bounce-chevron": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(6px)" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(0.8)" },
        },
        "flow-travel": {
          "0%": { strokeDashoffset: "100" },
          "100%": { strokeDashoffset: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bounce-chevron": "bounce-chevron 2s ease-in-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "flow-travel": "flow-travel 3s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
