"""initial_schema

Revision ID: 14cdd47b97b4
Revises: 
Create Date: 2026-06-09 19:54:32.512720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '14cdd47b97b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'date', name='uq_daily_metrics')
    )
    op.create_index(op.f('ix_metrics_daily_entity_id'), 'metrics_daily', ['entity_id'], unique=False)
    op.create_table('metrics_weekly',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('top_objection', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'week_start', name='uq_weekly_metrics')
    )
    op.create_index(op.f('ix_metrics_weekly_entity_id'), 'metrics_weekly', ['entity_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salespeople',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('device_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'BRAND_ADMIN', 'STORE_MANAGER', 'SALESPERSON', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('salesperson_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PREPROCESSING', 'TRANSCRIBING', 'DIARIZING', 'SEGMENTING', 'ANALYZING', 'SCORING', 'COMPLETED', 'FAILED', name='recordingstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('silence_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespeople.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_recording_id'), 'conversations', ['recording_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_label', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_recording_id'), 'transcript_segments', ['recording_id'], unique=False)
    op.create_table('conversation_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closing_attempt', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('coaching_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_analysis')
    op.drop_index(op.f('ix_transcript_segments_recording_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_conversations_recording_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('recordings')
    op.drop_table('users')
    op.drop_table('salespeople')
    op.drop_table('stores')
    op.drop_index(op.f('ix_metrics_weekly_entity_id'), table_name='metrics_weekly')
    op.drop_table('metrics_weekly')
    op.drop_index(op.f('ix_metrics_daily_entity_id'), table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_table('brands')
    # ### end Alembic commands ###
