"""add_speaker_role_corrections

Revision ID: 14ff67e4c4bf
Revises: c3d4e5f6g7h8
Create Date: 2026-06-12 04:06:11.858248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ff67e4c4bf'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_role_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_label', sa.String(length=20), nullable=False),
    sa.Column('original_role', sa.String(length=20), nullable=True),
    sa.Column('corrected_role', sa.String(length=20), nullable=False),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('new_confidence', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_role_corrections_recording_id'), 'speaker_role_corrections', ['recording_id'], unique=False)
    op.create_index(op.f('ix_speaker_role_corrections_user_id'), 'speaker_role_corrections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_role_corrections_user_id'), table_name='speaker_role_corrections')
    op.drop_index(op.f('ix_speaker_role_corrections_recording_id'), table_name='speaker_role_corrections')
    op.drop_table('speaker_role_corrections')
    # ### end Alembic commands ###
